cqna/urls.py
from django.urls import path

from . import views

app_name = 'cqna'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout, name='logout'),
    path('home', views.user_posts, name='user_posts'),
    path('create_post', views.create_post, name='create_post'),
    path('create_post/add_tags', views.add_tags, name='add_tags'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/edit_post/', views.edit_post, name='edit_post'),
    path('<int:post_id>/edit_tags/', views.edit_tags, name='edit_tags'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/reply/', views.reply, name='reply'),
    path('search_tag/', views.search_tag, name='search_tag'),
    path('search_user/', views.search_user, name='search_user'),
    path('search_detail/', views.search_detail, name='search_detail'),
    path('search/', views.call_search, name='search'),
#    path('register/',views.fun,name="regis"),
    path('register/',views.successregis, name="regis"),
    path('auto/',views.auto),
    path('tag_search/',views.tag_search),
    path('search_tag/', views.search_tag,name='done_now'),
    path('search_tag/', views.search_tag,name='add_now'),

]

project_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cqna/', include('cqna.urls')),
#    path("admin/", admin.site.urls),
]

cqna/models.py
from django.db import models

# Create your models here.

cqna/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import connection, transaction
from django.utils import timezone
from django.views.decorators.cache import cache_control
from django.contrib import messages
import re
from django.http import JsonResponse
# Create your views here.

# @cache_control(no_cache=True, must_revalidate=True, no_store=True)
# def index(request):
#     #post is not recognised POST is correct
#     if 'login_status' in request.COOKIES and 'UserID' in request.COOKIES:
#     #  print("fubuki atsuya")
#         return redirect("cqna:user_posts")
#     else:
#         cursor=connection.cursor()
#         val=(request.POST['num1'])
#         va=(request.POST['num2'])
#         rows=[]
     
#      #print(len(va)) it is empty thing
#         try:
#     #   print("&")
#             cursor.execute('''select password from users where id=%s'''%(val))
#             rows=cursor.fetchall()
#     #   print(rows)
#             if len(rows)!=0 and ((len(va)==0 and len(rows[0])==0) or (rows[0][0]==va)):
#     #    print("kalu")
#                 response= redirect("cqna:user_posts")
#                 response.set_cookie("UserID",val)
#                 response.set_cookie("login_status",True)
#                 request.session['logged_in'] = True
#                 request.session['user_id'] = val
#                 return response
#             else:
#                 messages.success(request,("Invalid UsedID/password"))
#                 return HttpResponse(render(request,'hello.html',{}))
#             cursor.close()
#         except Exception:
#             print("*")
#             messages.success(request,("Invalid UsedID/password"))
#             return HttpResponse(render(request,'hello.html',{}))

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
    if 'login_status' in request.COOKIES and 'UserID' in request.COOKIES:
    # if request.session.get('logged_in'):
        # print("kalu")
        return redirect("cqna:user_posts")
    else:
        if request.method == 'POST':
            # print("kalu2")
            val = request.POST.get('num1')
            va = request.POST.get('num2')
            if not val:
                error_message = 'Please enter user_id.'
                # print(error_message)
            elif not va:
                error_message = 'Please enter a password'
                # print(error_message)
            else:
                try:
                    val = int(val)
                    cursor = connection.cursor()
                    cursor.execute('''select password from users where id=%s'''%(val))
                    pas = cursor.fetchall()
                    cursor.close()
                    if pas:
                        pas = pas[0][0]
                        # print(pas)
                        response= redirect("cqna:user_posts")
                        response.set_cookie("UserID",val)
                        if va == pas:
                            response.set_cookie("login_status",True)
                            return response
                        else:
                            error_message = 'Invalid Password!!'
                    else:
                        error_message = 'User_id does not exist'
                except ValueError:
                    error_message = 'Invalid number entered.'
            context = {'error_message': error_message}
        else:
            context = {}
        # print(context)
        return render(request, 'hello.html', context)


# def index(request):
#     if request.session.get('logged_in'):
#         return redirect('cqna:user_posts')
#     if request.method == 'POST':
#         my_number_str = request.POST.get('my_number', '').strip()
#         my_password = request.POST.get('my_password', '').strip()
#         if not my_number_str:
        #     error_message = 'Please enter user_id.'
        # elif not my_password:
        #     error_message = 'Please enter a password'
#         else:
#             try:
#                 my_number = int(my_number_str)
#                 user_id = my_number
#                 cursor = connection.cursor()
#                 cursor.execute(''' select password from upass where user_id = %s '''%(user_id))
#                 pas = cursor.fetchall()
#                 cursor.close()
#                 if pas:
#                     pas = pas[0][0]
#                     request.session['user_id'] = user_id
#                     if my_password == pas:
#                         request.session['password'] = my_password
#                         request.session['logged_in'] = True
#                         return redirect('cqna:user_posts')
#                     else:
#                         error_message = 'Invalid Password!!'
#                 else:
#                     error_message = 'User_id does not exist'
#             except ValueError:
#                 error_message = 'Invalid number entered.'
#         context = {'error_message': error_message}
#     else:
#         context = {}
#     return render(request, 'cqna/index.html', context)

def fun(request):
 if 'login_status' in request.COOKIES and 'UserID' in request.COOKIES:
    print("*???")
    return redirect("home")
 else:
    return render(request,'wait.html')

# def successregis(request):
#     if 'login_status' in request.COOKIES and 'UserID' in request.COOKIES:
#         print("*???")
#         return redirect("home")
#     else:
#         if request.method == 'POST':
#             try:
#                 UserName = request.POST.get('')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def successregis(request):
    if 'login_status' in request.COOKIES and 'UserID' in request.COOKIES:
        print("*???")
        return redirect("home")
    else:
        if request.method == 'POST':
            try:
                UserName = request.POST.get('UserName')
                print(UserName)
                #val2=request.POST['num2']
                Location = request.POST.get('Location')
                print(Location)
                WrbUrl = request.POST.get('WrbUrl')
                print(WrbUrl)
                AboutMe = request.POST.get('AboutMe')
                print(AboutMe)
                password = request.POST.get('password')
                print(password)
                if password == '':
                    message = 'Please Fill the password'
                    context = {'message': message}
                    #messages.success(request,("Invalid Details"))
                    return render(request, "wait.html", context)
                else:    
                    #val7=request.POST['num7']
                    #print(val7)
                    
                    # now=datetime.datetime.now()
                    now = timezone.localtime(timezone.now())
                    print(now)
        #here the real problem was '%s'
                    cursor=connection.cursor()
                    cursor.execute('''insert into users (display_name, reputation, location, website_url, about_me, creation_date, last_access_date, password) values(%s, 0, %s, %s, %s, %s, %s, %s) ''', [UserName, Location, WrbUrl, AboutMe, now, now, password])
                    transaction.commit()
                    cursor.execute('''select last_value from users_id_seq''')
                    value=cursor.fetchall()

                    context={
                        'UserID': value[0][0],
                        'password': password
                    }
                    print(value[0][0], password)
                    cursor.close()
                    return render(request, 'success.html', context)
            except Exception:
                message = 'Invalid Details'
                context = {'message': message}
                #messages.success(request,("Invalid Details"))
                return render(request, "wait.html", context)
        else:
            return render(request, 'wait.html')

def user_posts(request):
    # if request.session.get('logged_in'):
    if 'login_status' in request.COOKIES and 'UserID' in request.COOKIES:
        user_id = int(request.COOKIES['UserID'])
        cursor = connection.cursor()
        cursor.execute(''' select title from posts where owner_user_id = %s and post_type_id = 1 order by creation_date desc'''%(user_id))
        val = cursor.fetchall()
        cursor.execute(''' select id from posts where owner_user_id = %s and post_type_id = 1 order by creation_date desc'''%(user_id))
        ids = cursor.fetchall()
        title_list = []
        id_list = []
        for v in val:
            title_list.append(v[0])

        for i in ids:
            id_list.append(i[0])
        
        data = []
        i = 0
        for id in id_list:
            data.append([id, title_list[i]])
            i = i+1

        context = {'data': data, 'user_id': user_id}
        
        cursor.close()
        
        return render(request, 'cqna/user_posts.html', context)

    else:
        context = {}
        return render(request, 'hello.html', context)

def split_tags_list(tag_string):
    tags = []
    fin_tags = []
    tags = tag_string.split('<')[1:]
    for b in tags:
        fin_tags.append(b.split('>')[0])
    return fin_tags

def make_tags_str(tags):
    if tags:
        tag_str = '<'
        for a in tags[:-1]:
            tag_str = tag_str + a + '><'
        tag_str = tag_str + tags[-1] + '>'
    else:
        tag_str = ''
    return tag_str

def tag_check(tag):
    cursor = connection.cursor()
    cursor.execute(''' select tag_name from tags where tag_name = %s ''', [tag])
    tag_name = cursor.fetchall()
    cursor.close()
    if tag_name:
        return True
    else:
        return False

def detail(request, post_id):
    if 'login_status' in request.COOKIES and 'UserID' in request.COOKIES:
        u_id = int(request.COOKIES['UserID'])
        # print(type(u_id))

cqna/templates/cqna/add_tags.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>

<form action="{% url 'cqna:add_tags' %}" method="post">
	{% csrf_token %}
	<div class="page"><!-- style="padding-left: 20px; display: inline-block; vertical-align: top;"> -->
	<label for="tag" style="padding-right: 14px;">enter tag</label>
	<input type="text" id="tag" name="tag"><br/><br/>
	<input class="button" type="submit" value="add" name="add">
	<input class="button" type="submit" value="done"name="done">
	</div><br/>
<div class="page" >
	{% if error_message %}
	<p style="color: red;">{{ error_message }}</p>
	{% endif %}
	</div>
	<div class="page">
		<p style="line-height: 1.8;">
	{% if tags %}
		{% for t in tags %}
			<span style="border: 1px solid black; white-space: nowrap; padding: 3px;">{{ t }}</span>
		{% endfor %}
	{% endif %}
		</p></div>
</form>

cqna/templates/cqna/create_post.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>

<div class="page">
<form method="post">
	{% csrf_token %}
	<div style="padding-left: 40px; padding-top: 20px; display: inline-block; vertical-align: top;">
		<h3>Post Title</h3>
		{% if message %}<p><strong style="color: red;">{{ message }}</strong></p>{% endif %}
		<textarea class="title example" name="post_title"></textarea><br/>
		<h3>Write post content below</h3>
		{% if message %}<p><strong style="color: red;">{{ message }}</strong></p>{% endif %}
		<textarea class="content example" name="post_text"></textarea><br/>
		<div style="padding-left: 0px; padding-top: 20px;">
			<input class="button" type="submit" value="post" /> <a href="{% url 'cqna:index' %}"><input class="button" type="button" value="cancel"></a></div>
	</div>
</form>
</div>

cqna/templates/cqna/detail.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">
<body class="example">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:user_posts' %}">Home</a>
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a> 
</div>
<br/><br/>
<fieldset><!--  style="width: 1000px; display: inline-block; vertical-align: top;">   -->
	<legend style="text-align: center;"><h2>{{ post_title }}</h2></legend>
	<div style="width: 1000px;"><p>{{ body|safe }}</p></div>
</fieldset>
<div class="page">	<h3>Related Tags</h3>
</div>
<div class="page"><!--  style="width: 90%; padding-left: 25px;"> -->
	<p style="line-height: 1.8;">
	{% if tags %}
	{% for tag in tags %}
		<span class="tags"> {{ tag }}</span> <!-- style="border: 1px solid black; white-space: nowrap; padding: 3px;">{{ tag }}</span> -->
	{% endfor %}
	{% endif %}
	</p></div>
	<!-- <div><p style="font-family: Unbounded; font-size: 17px;"><strong>Posted by:</strong> User_{{ u_id }} </p></div> -->
	<div class="page"> <!-- style="padding-top: 10px; padding-left: 3px;"> -->
	{% if is_owner %}
	<a href="{% url 'cqna:edit_post' post_id %}"><input class="button3" type="button" value="Edit post"></a><a href="{% url 'cqna:delete_post' post_id %}"><input class="button3" type="button" value="Delete post"></a>
	{% else %}
	<a href="{% url 'cqna:reply' post_id %}"><input class="button3" type="button" value="reply" ></a>
	{% endif %}
</div>
<div class="page"><p style="font-family: Unbounded; font-size: 17px;"><strong>Posted by:</strong> User_{{ u_id }} </p>
</div><br/><br/>
<div class="page">
<h2>Replies</h2></div>
{% if Replies %}
{% for row in Replies %}
<fieldset><!--  style="width: 1000px; display: inline-block;"> -->
	<legend><h3>user_{{ row.0 }}</h3></legend>
	<div style="width: 1300px;">{{ row.1|safe }}</div>
</fieldset>
{% endfor %}
{% else %}
<h4 style="text-align:center">No replies Yet!!</h4>
{% endif %}
</body>

cqna/templates/cqna/edit_post.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:user_posts' %}">Home</a>
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>


<!-- <h2>EDIT POST</h2> -->
<div class="page">
<form method="post">
	{% csrf_token %}
	<h3>Post Title</h3>
	{% if message %}<p><strong style="color: red;">{{ message }}</strong></p>{% endif %}
	<textarea class="title example" cols="25" rows="1" name="post_title">{{ title }}</textarea><br/>
	<h3>Write post content below</h3>
	{% if message %}<p><strong style="color: red;">{{ message }}</strong></p>{% endif %}
	<textarea class="content example" cols="35" rows="8" name="post_text">{{ body|safe }}</textarea><br/>
	<div style="padding-left: 0px; padding-top: 20px;">
	<input class="button" type="submit" value="post"/>
	<a href="{% url 'cqna:detail' post_id %}"><input class="button" type="button" value="cancel"></a>
</div>
</form>
</div>

cqna/templates/cqna/index.html
<form action="{% url 'cqna:index' %}" method="post">
	{% csrf_token %}
	<label for="user_id" style="padding-right: 14px;">Enter user_id:</label>
	<input type="text" id="user_id" name="my_number" required><br/>
	<label for="my_password">Enter password:</label>
	<input type="password" id="my_password" name="my_password" required>
	{% if error_message %}
		<p style="color: red;">{{ error_message }}</p>
	{% endif %}
	<button type="submit">Submit</button>
</form>

cqna/templates/cqna/reply.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>
<br/><br/>

<fieldset><!--  style="width: 1000px; display: inline-block; vertical-align: top;">  -->
<legend><h3>{{ post_title }}</h3></legend>
<div style="width: 1000px;"><p>{{ body|safe }}</p></div>
</fieldset>

 <div class="page"><!--</div> style="width: 600px; display: inline-block; vertical-align: top; padding-left: 25px;"> -->
	<h4>Related Tags</h4></div><div class="page">
	{% if tags %}
	{% for tag in tags %}
	<span class="tags">{{ tag }}</span>
	{% endfor %}
	{% endif %}
</div>

<form method="post">
	{% csrf_token %}
	<div class="page">
	<h3>Reply</h3></div>
	{% if message %} <p><strong style="color: red;">{{ message }}<strong></p> 
	{% endif %}
	<textarea class="content example" name="reply_text"></textarea><br/fieldset>
	<div class="page"> <input class="button" type="submit" value="reply"/>
	<a href="{% url 'cqna:detail' post_id %}"><input class="button" type="button" value="cancel"></a></div>
</form>

cqna/templates/cqna/search.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:user_posts' %}">Home</a>
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>

<div class="page" style="margin-top: 8.5%;">
<a href="{% url 'cqna:search_user' %}">
<button class="button" ><!-- style="position: absolute; top: 30px; left: 30px;"-->Search by user</button>
</a>
	<a href="{% url 'cqna:search_tag' %}">
<button class="button"><!-- style="position: absolute; top: 30px; left: 150px;" -->Search by tag</button>
	</a>
</div>

cqna/templates/cqna/search_detail.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">
<body class="example">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:user_posts' %}">Home</a>
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>

{% if tag %}
<h1>Posts with the tags:</h1>
{% for t in tags %}

<span style="border: 1px solid black; white-space: nowrap; padding: 3px;">{{ t }}</span>
{% endfor %}
{% elif s_user %}
<h1>user_{{ s_user }}'s Posts</h1>
{% endif %}
<br/>
{% if id_title %}
<div class="page">
<ul>
	{% for row in id_title %}
	<a href="{% url 'cqna:detail' row.0 %}" style="font-weight: 	bold; text-decoration: none; color: black;">
		<div class="button2" style="margin-bottom: 1.5px; width: 1000px; height: 50px; display : flex; align-items: center; justify-content: center;"> 
			 {{ row.1 }}
			 {# {{ forloop.counter }} #}
		 </div>
	</a> 
	{% endfor %}
</ul></div>
{% else %}
<h4>{{ message }}</h4>
{% endif %}

</body>

cqna/templates/cqna/search_tag.html
<!-- {% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:user_posts' %}">Home</a>
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>

<form action="{% url 'cqna:search_tag' %}" method="post">
{% csrf_token %}
<div class="page"> style="padding-left: 20px; display: inline-block; vertical-align: top;">
	<label for="tag" style="padding-right: 14px;">enter tag</label>
		<input type="text" id="tag" name="tag"><br/>
		<input class="button" type="submit" value="add" name="add">
		<input class="button" type="submit" value="done"name="done"><br/>
</div><br/>
<div class="page" >
	{% if error_message %}
	<p style="color: red;">{{ error_message }}</p>
	{% endif %}
</div><br/>
<div class="page style="width: 400px; padding-left: 20px; display: inlineine-block; vertical-align: top;"><p style="line-height: 1.8
	<p style="line-height: 1.8;">
	{% if tags %}
		{% for t in tags %}
			<span style="border: 1px solid black; white-space: nowrap; padding: 3px;">{{ t }}</span>
		{% endfor %}
	{% endif %}
	</p></div>
	</form> -->

	{% load static %}
	<!DOCTYPE html>
	<html lang="en">
	<head>
	<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css"/>
	<script src="https://unpkg.com/@trevoreyre/autocomplete-js"> </script>
	</head>
	<body>
	<div class="navigator">
		<a class="navigator a" href="{% url 'cqna:user_posts' %}">Home</a>
		<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
		<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
	</div>
	
	
	
	
	
	<div class="container">
			<label for="user_id">enter tags</label>
			<div id="autocomplete" class="autocomplete">
				<input class="autocomplete-input" name="s_user">
				
				<ul class="autocomplete-result-list"></ul>
			  </div>
			  <form action="/cqna/search_tag/" method='post'>
				{% csrf_token %}
				<input type="hidden" id="taggg" name="taggg"><br/>
				<input class="button" type="submit" value="add" name="add_now">
				<input class="button" type="submit" value="done"name="done_now"><br/>
				<!-- {% if error_message %}
				<p style="color: red;">{{ error_message }}</p>
				{% endif %} -->
				<div class="page" >
					{% if error_message %}
					<p style="color: red;">{{ error_message }}</p>
					{% endif %}
				</div><br/> 
				<div class="page"><!--style="width: 400px; padding-left: 20px; display: inlineine-block; vertical-align: top;"><p style="line-height: 1.8;">-->
					{% if tags %}
					{% for t in tags %}
					<span style="border: 1px solid black; white-space: nowrap; padding: 3px;">{{ t }}</span>
					{% endfor %}
					{% endif %}
					</p></div>
				
			</form>
	<script>
		new Autocomplete('#autocomplete', {
			search: input => {
			  console.log(input)
			  const encodedInput = encodeURIComponent(input);
			  const url=`/cqna/tag_search/?search=${encodedInput}`
			  console.log(url)
			  return new Promise(resolve =>{
				fetch(url)
				.then(response=>response.json())
				.then(data =>{
					console.log(data.payload)
					resolve(data.payload)
				})
			  })
			},
		onSubmit: result => {
		// window.open(`/search_user/?s_user=${result}`)
				var input_value=document.getElementById('taggg');
				input_value.value=result
	// var suubmit_button = document.getElementById('submitbut');
	// suubmit_button.click()
	}
		})

		
	</script>
	</div>
	
	</body>
	
	</html>

cqna/templates/cqna/user_posts.html
{% load static %}

<link rel="stylesheet" href="{% static 'cqna/style_8.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Unbounded&display=swap" rel="stylesheet">
<body class="example">

<div class="navigator">
	<a class="navigator a" href="{% url 'cqna:logout' %}">Logout</a>
	<a class="navigator a" href="{% url 'cqna:search' %}">Search</a>
</div>

<h1>User-{{ user_id }}'s Posts</h1>
{% if data %}
<div class="page">
<ul>
	{% for row in data %}
	 <a href="{% url 'cqna:detail' row.0 %}" style="font-weight: bold; text-decoration: none; color: black; width: 1000px; height: 50px;">
		 <div class="button2" style="margin-bottom: 1.5px; width: 1000px; height: 50px; display : flex; align-items: center; justify-content: center;"> 
			{{ row.1 }}
			{# {{ forloop.counter }} #}
		 </div>
	 </a> 
	{% endfor %}
</ul>
</div>
{% else %}
<p>No posts are available.</p>
{% endif %}
<div class="navigatoropp">
<a class="navigatoropp a" href="{% url 'cqna:create_post' %}">
	<!-- <button class="button"> -->
	Create New Post
<!-- </button>style="margin-left: 40px;"> -->
	</a></div>


</body>